logging:
  level:
    ROOT: INFO
    ru.ilya.zoo: DEBUG
    org.springframework: INFO

server:
  port: ${PORT_TO_EXPOSE:8080}

jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      default_schema: public
      user_sql_comments: true
      format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zoo?currentSchema=public
    username: ${DATASOURCE_USER:zoo}
    password: ${DATASOURCE_PASSWORD:123}

  liquibase:
    enabled: true
    change-log: classpath:database_zoo_changelog.xml
    parameters:
      schema: zoo
