version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: 123

    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 8081:80

  app:
    depends_on:
      - db
    image: iliapoliakov/zoo:latest
    container_name: zoo
    restart: always
    ports:
      - 8080:8080